### PR TITLE
update dependencies to compile in Rust >1.77

### PR DESCRIPTION
**Pull request by pluiedev**
In 1.77, `#[feature(int_roundings)]` was stabilized and old versions of `num` had a name conflict that prevents it from compiling.

### CODE REVIEW

**Comment by Wulfsta** [comment]
I’m amazed anyone is using this - I’ll test later this week.

**Comment by pluiedev** [comment]
> I’m amazed anyone is using this - I’ll test later this week.

I only caught this because it's failing to build on NixOS's CI systems and we're in the middle of the process to minimize broken packages before a release :P

**Comment by Wulfsta** [comment]
@pluiedev should be fixed - I don't think that package has any `updateScript` in nixpkgs, so you will have to bump this manually.

**Comment by Wulfsta** [comment]
Oh looks like the bot caught it, cool.

**Pull request merged**
